### ISSUE TITLE
Fix leaking HUD from showing in Mission Control

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/turntouch-mac#10]
See the Desktop at the top left of this image? The HUD is showing in expose/mission control and it shouldn't. This has been there since day 1 but I never figured out how to fix it.

<img width="1440" alt="Screen Shot 2019-11-24 at Nov 24 1 04 41 PM" src="https://user-images.githubusercontent.com/44229/69498916-1a3b7980-0ebb-11ea-8fcb-a4f239776b24.png">

**Comment by Dejal** [comment]
An `orderOut:` in the fadeout completion handler was commented out; restoring that seems to solve the issue. I don't know why it was commented out; it seems to have been so since you originally wrote it.
