### ISSUE TITLE
Keynote not working

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/turntouch-mac#12]
Not sure why, but the Presentation app isn't working with keynote. It can find the app and activate it, but there are no documents or windows in the SBApplication object.

**Comment by Dejal** [comment]
It appears you fixed this? I am able to control Keynote without difficulty.  (I did remove some duplicates in the Keynote.h header, but I doubt that would have been an issue.)

Please close this if no longer an issue, or clarify if it is.

**Comment by samuelclay** [comment]
Just checked and it works. Don't know why it didn't but all's well.

**Comment by samuelclay** [comment]
Can confirm this is working now. Probably just needed a reboot.
