### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/turntouch-mac#13]
I'd like to see Turn Touch gain support for keyboard shortcuts on Mac. Personally these are what I want:

* control+option+shift+up Music volume up
* control+option+shift+down Music volume down
* control+option+down Music play/pause
* control+option+up Music HUD

All of these particular actions show the Music HUD, the last one just does nothing but show the song title like the Alarm Clock app does (hit Preview in Alarm to see it).

The keyboard shortcut icon should appear next to the rename action icon (so only when you've hit Change on an Action). Have it show a keyboard shortcut chooser, with those above as defaults.

Here's the icon:
![icons8-keyboard-96](https://user-images.githubusercontent.com/44229/72672762-6a533a00-3a2d-11ea-9000-1485b14a8b67.png)

**Comment by Dejal** [comment]
What would you envision for the UI to set the shortcut for the Music HUD?  Not editing an action in that case.

**Comment by samuelclay** [comment]
Maybe the mode options view has a table of keyboard shortcuts for each action? Or perhaps just the single music HUD item. It can be a single line for that one action.

**Comment by Dejal** [comment]
I like the idea of the shortcut being edited from change action, like renaming. I don't think having a table of all actions makes sense in that context. But I could add an actions options view (like the music playlist options) for music mode, with a second shortcut control to show the HUD.

**Comment by Dejal** [comment]
I've added a third-party shortcut control to the project (the same one I use in my Time Out app), and written up some notes on the implementation, but will actually do this next month. Not enough time left this month, and we might want to think about the UI some more.

**Comment by samuelclay** [comment]
Amazing! Love the UI. Ok, so we should make this a little bit more discoverable, but first, I couldn't get the keyboard shortcut working that spurred this ticket. Control+Option+Shift+Up won't record because of the up key. Same for down. I want it to control iTunes volume. 

As a note, Control+option+down does record correctly, for play/pause.

**Comment by samuelclay** [comment]
Also, can we move the keyboard shortcut to the right of the Action Title, similar to how authors are displayed on NewsBlur's web story titles list.

**Comment by samuelclay** [comment]
Also, let's turn on the Rename and Keyboard icons all the time, without having to hit Change first. I think that's fine since you're already opening an Action, so it won't be visible all the time.

**Comment by samuelclay** [comment]
Eventually we're going to have to offer keyboard shortcuts for actions that aren't tied to the remote. And then we'll have created an entirely new app but that's great!

**Comment by Dejal** [comment]
If a shortcut doesn't record, it may be taken by something else in the system.  Check your Keyboard System Preferences.

There isn't room for the shortcut control to the right of the action title.  I tried that at first, and tried replacing the title when the shortcut was being edited, but found having it below was better. I could display it to the right when not editing it, but that'd be less consistent.

**Comment by samuelclay** [comment]
I double checked every single keyboard shortcut and couldn't find a single one that had the up/down arrow keys. Mission Control had left/right, but both were unchecked.

**Comment by Dejal** [comment]
I'm able to assign the Ctrl-Option-Shift-Up shortcut:

<img width="426" alt="Screen Shot 2020-03-10 at 19 09 42" src="https://user-images.githubusercontent.com/1318849/76375702-b7ec7480-6303-11ea-87d9-abb8240cbbb5.png">

It should have displayed an alert if the system was using it for something. Try again?

**Comment by Dejal** [comment]
How's this looking now? Please close this issue if working fine, or provide more info if there are any problems.

**Comment by samuelclay** [comment]
Yep, it's been working, I think maybe a reboot or OS point upgrade fixed the keyboard shortcut issue.
