### ISSUE TITLE
Missing Effra font

### ISSUE THREAD

**Issue by Dejal** [samuelclay/turntouch-mac#3]
Many of the xibs and the code references an "Effra" font, which doesn't seem to be bundled with the app, and isn't a standard font. 

Opening such xibs gives a warning:

> Font “Effra-Regular” does not exist on this system, substituting the system font instead. Saving the document will lose the original font reference.

This means that all users of the app, other than you and whoever else may have that font, would see a different appearance.

If the font can be bundled with the app, please add it to the repo. Otherwise, I can revert uses to the system font, or another of your choosing.

**Comment by samuelclay** [comment]
It's in [Turn Touch Mac/Resources/fonts](https://github.com/samuelclay/turntouch-mac/tree/master/Turn%20Touch%20Mac/Resources/fonts). And I can confirm that I see Effra on other user's machines. (Basically all of my friends have their own remote and I've been there to install the app on their machine.)

**Comment by Dejal** [comment]
Ah. Yes, it is bundled with the app, so it's just an Xcode issue with editing the xib.  My bad.  Installing the font on my Mac fixes that.

**Comment by samuelclay** [comment]
I think you'll want the light and bold versions that are found on the iOS repo's fonts dir. But I thought the Mac app would use them, but I suppose not.
