### ISSUE TITLE
Catalina support

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/turntouch-mac#6]
Sounds like it crashes. 

https://forum.turntouch.com/t/cant-pair-on-mojave/322

**Comment by Dejal** [comment]
Can we get some clarification on this. I am able to pair my remote on Mojave (10.14.6) without difficulty. Did they mean Catalina perhaps (I haven't tested that yet)?

Please confirm the issue, and perhaps a crash report or screen recording might be helpful.

**Comment by samuelclay** [comment]
Yep, Catalina. It seems Mojave is the release that I stopped remembering the names of OS X releases.

**Comment by samuelclay** [comment]
Works now on Catalina.
