### ISSUE TITLE
Crash on start - [ITunesApplication sources]: unrecognized selector

### ISSUE THREAD

**Issue by samuelclay** [samuelclay/turntouch-mac#7]
See this issue: https://forum.turntouch.com/t/macos-application-unable-to-start/324/7

I'm not sure why the `[ITunesApplication sources]` method isn't found, but I'd like to protect against this crash.

**Comment by Dejal** [comment]
I notice that the customer said they were using macOS Sierra 10.12.6.  I don't have a Mac using that older OS version, so can't test on it (I have High Sierra, Mojave, and Catalina).  But it wouldn't surprise me if the iTunes app's scripting bridge methods were different back then.  I've added a guard against that crash, but it may crash elsewhere.

While I generally maintain backwards compatibility as long as possible, I'd suggest that for an app like this, you might need to be more restrictive.

**Comment by samuelclay** [comment]
Agreed
